# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stephen Nixon
email: stephen@thundernixon.com
description: > # this means to ignore newlines until "baseurl:"
  This is the portfolio of Stephen Thunder Nixon, product / identity / type / graphic designer.
baseurl: "/portfolio2016" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: thundernixon
github_username:  thundernixon

# Build settings
markdown: kramdown
permalink: pretty

# # Assets Pipeline
# assets:
#   sources:
#     - _assets
#     - _assets/fonts
